# Generated by Django 3.1.1 on 2020-10-06 13:20

from django.db import migrations

def insert_default_terms(apps,schema_editor):
        Term = apps.get_model('Term','Term') # create instance of Term module
        term = Term(details='Edit Me')
        term.save()


class Migration(migrations.Migration):

    dependencies = [
        ('Term', '0001_initial'),
    ]
    
    operations = [
        migrations.RunPython(insert_default_terms), # python manage.py migrate
    ]
